# Site settings
title: Julius Hermanto's Portfolio
description: A portfolio site about Julius Hermanto.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: https://juliushmto.github.io # the base hostname & protocol for your site e.g. https://maulana-kurniawan.github.io

# User settings
user_name: Julius Hermanto
user_title: Data Science, Data Visualization, and Machine Learning
user_description: With three years of experience in the IT industry, particularly in the banking and F&B sectors as a software engineer, I am an aspiring Data Scientist with a strong foundation in statistical analysis, machine learning, and data visualization. I am adept at applying data analysis and modeling concepts using Python, SQL, and Amazon's AWS. I exhibit a strong desire to learn and adapt to new technologies and approaches and am prepared to take on new challenges in the process of gaining insightful knowledge from data for business optimization. A proactive team player with strong problem-solving skills, I am passionate about using data to extract insights that will propel business success.
email: juliushmto@gmail.com
linkedin: juliushermanto
github: JuliusHmto
gitlab:
facebook: 
instagram: 
threads:
twitter:
telegram:
discord:
tiktok:
medium: juliushmto
kaggle: juliushermanto

# Google-analytics
google-analytics:
  id: "" # Leave it blank if you don't want to use Google Analytics

collections:
  projects:
    output: false

sass:
  sass_dir: _sass
  sourcemap: never

plugins:
  - jekyll-seo-tag

exclude: ["Gemfile*", "LICENSE", "README.md"]
